import type { WizardNode } from '@/entities/topic'

export const ANSIBLE_WIZARD_TREE: Record<string, WizardNode> = {
  start: {
    q: "What Ansible failure or unexpected behavior are you facing?",
    options: [
      { label: "UNREACHABLE! SSH connection or host authentication failed", next: "ssh_unreachable" },
      { label: "FAILED! Permission denied / 'sudo: a password is required'", next: "sudo_permission" },
      { label: "FAILED! 'The task includes an option with an undefined variable'", next: "undefined_variable" },
      { label: "A notified handler did NOT run or restart the service", next: "handler_not_running" },
      { label: "ERROR! 'couldn't resolve module/action' (Module not found / FQCN error)", next: "module_not_found" },
      { label: "Ansible Vault: 'Decryption failed (no vault secrets found)' or wrong password", next: "vault_decryption" },
      { label: "Task is always reporting 'changed: true' even when nothing changed (idempotency broken)", next: "broken_idempotency" },
    ],
  },

  ssh_unreachable: {
    q: "Which specific SSH error message is displayed?",
    options: [
      { label: "Host key verification failed / Host key changed", next: "host_key_error" },
      { label: "Permission denied (publickey, password)", next: "ssh_auth_error" },
      { label: "Connection timed out / Network unreachable", next: "network_timeout" },
    ],
  },

  host_key_error: {
    result: true,
    title: "Fix SSH Host Key Verification Failure",
    body: "When managed nodes are re-provisioned or have new IPs, SSH rejects the connection because the host key in `~/.ssh/known_hosts` doesn't match.",
    cmds: [
      "# Solution 1: Remove the old stale host key for that specific host",
      "ssh-keygen -R <hostname_or_ip>",
      "",
      "# Solution 2: Disable host key checking in ansible.cfg (Common for dynamic/CI environments)",
      "# In your ansible.cfg file:",
      "[defaults]",
      "host_key_checking = False",
      "",
      "# Or pass via environment variable:",
      "export ANSIBLE_HOST_KEY_CHECKING=False",
    ],
  },

  ssh_auth_error: {
    result: true,
    title: "Fix SSH Public Key / Password Authentication",
    body: "Ansible cannot log in to the target machine using the default user or key.",
    cmds: [
      "# 1. Test manual SSH connection with verbose output:",
      "ssh -vvv -i ~/.ssh/my_private_key.pem ubuntu@<target-ip>",
      "",
      "# 2. Specify the correct remote user and private key in inventory:",
      "# In inventory.ini:",
      "webserver1 ansible_host=192.168.1.50 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519",
      "",
      "# 3. Or pass via command line flags:",
      "ansible -i inventory.ini all -m ping -u ubuntu --private-key=~/.ssh/id_ed25519",
    ],
  },

  network_timeout: {
    result: true,
    title: "Resolve Network Timeout / Unreachable Host",
    body: "The control node cannot route to the managed node, or firewall/security groups block port 22 (SSH) or port 5986 (WinRM).",
    cmds: [
      "# 1. Check network connectivity and port 22 reachability:",
      "nc -zv -w5 <target-ip> 22",
      "",
      "# 2. Verify cloud security group (AWS EC2 Security Group / GCP Firewall) allows inbound port 22 from your control node IP.",
      "",
      "# 3. If using a bastion / jump host, configure ProxyJump in ansible.cfg or ssh.cfg:",
      "[ssh_connection]",
      "ssh_args = -o ProxyJump=jumpuser@bastion.company.com",
    ],
  },

  sudo_permission: {
    result: true,
    title: "Configure Sudo Privilege Escalation ('become')",
    body: "The remote user needs root privileges to install packages or manage system services, but sudo requires a password or passwordless sudo is not configured.",
    cmds: [
      "# Option A: Run playbook and prompt for the remote sudo password (-K / --ask-become-pass)",
      "ansible-playbook -i inventory.ini site.yml --ask-become-pass",
      "",
      "# Option B: Enable passwordless sudo for the ansible user on the remote node (Best practice):",
      "# On the target server, edit /etc/sudoers.d/ansible:",
      "echo 'ansible ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/ansible",
      "sudo chmod 0440 /etc/sudoers.d/ansible",
      "",
      "# In your playbook, ensure become is declared:",
      "- hosts: all",
      "  become: true",
      "  tasks:",
      "    - name: Install nginx",
      "      ansible.builtin.apt:",
      "        name: nginx",
      "        state: present",
    ],
  },

  undefined_variable: {
    result: true,
    title: "Resolve Undefined Variable Errors",
    body: "Ansible failed because a referenced variable is not defined in any scope (host_vars, group_vars, playbook vars, role defaults, or extra vars).",
    cmds: [
      "# 1. Provide a fallback default value using Jinja2 'default' filter:",
      "# Replace: {{ app_port }}",
      "# With:    {{ app_port | default(8080) }}",
      "",
      "# 2. Pass the variable dynamically via command line extra vars (-e):",
      "ansible-playbook -i inventory.ini site.yml -e 'app_port=3000 env=production'",
      "",
      "# 3. Verify variable spelling and ensure the role includes 'defaults/main.yml' or 'vars/main.yml'.",
    ],
  },

  handler_not_running: {
    result: true,
    title: "Diagnose Why a Handler Did Not Fire",
    body: "Handlers only run if: (1) the notifying task reported 'changed: true', AND (2) the play finishes without any preceding task failing.",
    cmds: [
      "# 1. Check if the task actually made a change. If the file was already up to date, changed=false and handler will NOT fire!",
      "",
      "# 2. Check if a later task failed in the play. If any task fails, handlers are skipped by default. To force handlers on failure:",
      "- hosts: all",
      "  force_handlers: true",
      "  tasks: ...",
      "",
      "# 3. To trigger handlers immediately in the middle of a play instead of waiting for the end:",
      "- name: Flush all pending handlers right now",
      "  ansible.builtin.meta: flush_handlers",
    ],
  },

  module_not_found: {
    result: true,
    title: "Resolve Missing Module / FQCN Error",
    body: "Modern Ansible (v2.10+) split all non-core modules into independent collections (e.g. community.general, amazon.aws, kubernetes.core).",
    cmds: [
      "# 1. Install required collection via ansible-galaxy:",
      "ansible-galaxy collection install community.general",
      "ansible-galaxy collection install amazon.aws",
      "",
      "# 2. Or create a requirements.yml file in your project:",
      "# collections:",
      "#   - name: community.general",
      "#   - name: amazon.aws",
      "ansible-galaxy install -r requirements.yml",
      "",
      "# 3. Use Fully Qualified Collection Names (FQCN) in tasks:",
      "- name: Manage UFW firewall",
      "  community.general.ufw:",
      "    rule: allow",
      "    port: '80'",
    ],
  },

  vault_decryption: {
    result: true,
    title: "Resolve Ansible Vault Password Issues",
    body: "Ansible cannot decrypt an encrypted file or encrypted inline variable (`!vault | ...`).",
    cmds: [
      "# 1. Prompt interactively for vault password:",
      "ansible-playbook -i inventory.ini site.yml --ask-vault-pass",
      "",
      "# 2. Use a secure vault password file (or script):",
      "ansible-playbook -i inventory.ini site.yml --vault-password-file ~/.vault_pass.txt",
      "",
      "# 3. To view or edit the encrypted secret without running the playbook:",
      "ansible-vault view group_vars/all/vault.yml --vault-password-file ~/.vault_pass.txt",
      "ansible-vault edit group_vars/all/vault.yml --vault-password-file ~/.vault_pass.txt",
    ],
  },

  broken_idempotency: {
    result: true,
    title: "Fix Tasks Always Reporting 'changed: true'",
    body: "Tasks using raw `ansible.builtin.command` or `ansible.builtin.shell` will ALWAYS report changed because Ansible cannot know what your arbitrary bash script did.",
    cmds: [
      "# Solution 1: Use creates or removes parameters to skip if file exists:",
      "- name: Extract tarball only if destination directory is missing",
      "  ansible.builtin.command: tar -xzf /tmp/app.tar.gz -C /opt/app",
      "  args:",
      "    creates: /opt/app/bin/start.sh",
      "",
      "# Solution 2: Use changed_when to inspect output return codes or stdout:",
      "- name: Check cluster status",
      "  ansible.builtin.command: /usr/local/bin/check_sync.sh",
      "  register: sync_result",
      "  changed_when: \"'RESYNC_PERFORMED' in sync_result.stdout\"",
      "",
      "# Solution 3: Whenever possible, replace shell scripts with native idempotent modules (copy, template, git, apt, service)!",
    ],
  },
}
