export * from './types'
export { dockerCourse } from '@/entities/docker'
export { k8sCourse } from '@/entities/k8s'
export { jenkinsCourse } from '@/entities/jenkins'
export { gitCourse } from '@/entities/git'
export { ansibleCourse } from '@/entities/ansible'
export { artifactoryCourse } from '@/entities/artifactory'
